
on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: build
        run: sudo apt update; sudo apt install debhelper devscripts; git clone https://github.com/SapphicLinux/base-files.git; cd base-files;sudo chmod +x ./build.sh;sudo ./build.sh
