
on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: install reqs
        run: apt update && apt install devscripts fakeroot
      - name: clone repo
        run: git clone https://github.com/SapphicLinux/base-files.git && cd base-files
      - name: script
        run: sudo ./build.sh
