
on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: get gpg key
        run: gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys '4D64 FEC1 19C2 0290 67D6 E791 F8D2 585B 8783 D481'
      - name: import gpg key
        run: gpg --output debian-archive-bookworm-stable.pgp --export '4D64 FEC1 19C2 0290 67D6 E791 F8D2 585B 8783 D481'
      - name: testt
        run: whoami
      - name: fix apt?
        run: curl -o build.sh https://raw.githubusercontent.com/SapphicLinux/base-files/main/build.sh && chmod +x ./build.sh
      - name: script
        run: sudo ./build.sh
