
on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: fix apt?
        run: curl -o build.sh https://raw.githubusercontent.com/SapphicLinux/base-files/main/build.sh && chmod +x ./build.sh
      - name: script
        run: sudo ./build.sh
