name: build deb package
  on:
    push:
     branches:
      - main
    schedule:
    - cron: "0 2 * * *"
    workflow_dispatch:
  jobs:
    build:
      name: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: /build.sh
